version: '3.8'

services:
  ws-server:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/server/node_modules
    working_dir: /app/server
    command: node index.js
